"""This notebook is introduction to the competition [Wattbot 2025](https://www.kaggle.com/competitions/WattBot2025/overview)"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_eda.ipynb.

# %% auto 0
__all__ = ['data_path', 'metadata', 'train', 'get_train_data', 'get_value', 'test', 'is_arxiv', 'download_pdf', 'compute_tokens']

# %% ../nbs/00_eda.ipynb 4
import random
import tiktoken
import time
import urllib
from collections import Counter
import pandas as pd
import contextkit.read as rd
import fastcore.all as fc

# %% ../nbs/00_eda.ipynb 7
data_path = fc.Path(fc.Path.cwd().parent/'data')
data_path.ls(file_exts=['.csv'])

# %% ../nbs/00_eda.ipynb 8
def metadata(): return pd.read_csv(data_path/'metadata.csv', encoding='latin-1')

# %% ../nbs/00_eda.ipynb 11
def train(): return pd.read_csv(data_path/'train_QA.csv')

# %% ../nbs/00_eda.ipynb 13
def get_train_data(idx=-1):
    t = train()
    if idx == -1: idx = random.randint(0, len(t))
    return fc.NS(**t.iloc[idx])

# %% ../nbs/00_eda.ipynb 16
def get_value(row):
    return fc.NS(**row)

# %% ../nbs/00_eda.ipynb 18
def test(): return pd.read_csv(data_path/'test_Q.csv')

# %% ../nbs/00_eda.ipynb 24
def is_arxiv(url): return 'arxiv' in url

# %% ../nbs/00_eda.ipynb 31
def download_pdf(url): 
    url = url.strip()
    filename = data_path/fc.Path(url).name
    if filename.suffix != '.pdf': filename = filename.with_name(f"{filename.name}.pdf")
    if not filename.exists(): fc.urlretrieve(url, filename)
    return filename

# %% ../nbs/00_eda.ipynb 43
def compute_tokens(msg):
    tokens = encoding.encode(msg)
    return len(tokens)
