# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_utils.ipynb.

# %% auto 0
__all__ = ['fw', 'Reranker']

# %% ../nbs/05_utils.ipynb 3
import os
import openai
from dotenv import load_dotenv
import requests
import fastcore.all as fc

# %% ../nbs/05_utils.ipynb 5
def fw(): return openai.OpenAI(base_url="https://api.fireworks.ai/inference/v1", api_key=os.environ['FIREWORKS_API_KEY'])

# %% ../nbs/05_utils.ipynb 7
class Reranker:
    def __init__(self, model='accounts/fireworks/models/qwen3-reranker-8b', base_url="https://api.fireworks.ai/inference/v1", api_key=None):
        if api_key is None: api_key = os.environ['FIREWORKS_API_KEY']
        fc.store_attr()
        
    def rank(self, query, docs, n=10, return_documents=False, task="Given a web search query, retrieve relevant passages that answer the query"):
        ans = fc.L.range(len(docs))
        try:
            res = requests.post(f"{self.base_url}/rerank",
                json={"model": self.model, "query": query, "documents": list(docs), "top_n": n, "return_documents": False},
                headers={"Authorization": f"Bearer {self.api_key}", "Content-Type": "application/json"}
            )
            return fc.L(res.json()['data']).attrgot('index')
        except Exception as e:
            print(e)
        return ans
